name: React application

on:
  push:
      branches: [master]
  pull_request: 
      branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: docker login
          env:
            DOCKER_USER: ${{secrets.DOCKER_USER}}
            DOCKER_PASSWORD: ${{secrets.DOCKERPW}}
            repository: ${{secrets.DOCKER_USER}}/git_action_v2:latest
            tags: latest, ${{ secrets.DOCKER_TOKEN }}
          run: |
            docker login -u $DOCKER_USER -p $DOCKERPW
                   
        - name: List images
          run: docker images    
        - name: Docker Push
          run: docker push ${{secrets.DOCKER_USER}}/git_action_v2:latest

      
        
